### ISSUE TITLE
Fertigstellung Version 0.7.2

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#177]
- [x] Binnies Mod MineTweaker Änderungen wieder übernehmen. 
- [x] Änderungen/Neuerungen in Forestry und Binnies prüfen.
- [x] Warning nach ModTweaker2 update beseitigen oder bei vorheriger Version bleiben.
- [x] Prüfen welche Mods problemlos geupdatet werden können. ( Liste wird angehängt )
- [x] Natura entfernen? **ja +4** /~~nein~~ ( siehe https://github.com/combak/ShatteredWorld/issues/176 )
- [x] Neue Forest Day Version verfügbar? ~~ja~~ / **nein**
- [x] Aktuelles World Save sichern. ( 21.03.2016 )
- [x] The Spice of Life: Essen kann jetzt in mehreren Food Groups sein. => checken 

~~\- [ ] Hardcore Ender Expansion Musik Resource Pack wenn möglich via Resource Loader einbinden.~~ Optional zur nächsten Version prüfen

**Mods update?**
- [x] Adv. Generators updaten? **ja +2** / ~~nein~~
- Keine neuen Blöcke/Items
- Überwiegend fixes und imho nichts was gebalanced werden müsste.
- Forestry peat kann zu Syngas verarbeitet werden. 
- [x] AE2 Stuff updaten? **ja +3** / ~~nein~~
- Ein neuer Block der wireless P2P Verbindungen ermöglicht, wenn ich das richtig verstanden habe.
- Kann nur geupdatet werden, wenn Adv. Generators geupdatet wird, da die verwende BdLib Version nicht für AE2 Stuff funktioniert und das verwendete Adv. Generators nicht mit der aktuellsten BdLib Version. 
- [x] Extra Utilities updaten? **ja**/ ~~nein~~
- Neu Tiny und Large Chest, sehe ich eigentlich kein Problem
- Neu Ender Collector, kommt auf eine Kiste drauf und teleportiert gedropte Items in die Kiste, also quasi ein Vacuum Hopper
- Neu Trash Can in der Fluid variante wurde hinzugefügt.
- Fügt zu den Tinkers Materialien Bedrock, Magical Wood und Unstable Ingots hinzu, dass sollte geprüft werden wie stark das Material ist.  
- [x] Harvestcraft updaten? **ja** / ~~nein~~ ( siehe https://github.com/combak/ShatteredWorld/issues/178 )
- Drops aus den Gardens wurden verändert und erweitert.
- Extrem viel neue Rezepte
- Wenn Pams so weitermacht haben wir bald die komplette Nahrungskette in Minecraft. ^^
- Vielleicht sieht es mehr aus als es ist aber die Food Groups wird man trotzdem nochmal anpassen und checken müssen. 
- [x] Lycanite Mobs updaten? **ja +2** / ~~nein~~
- Fügt Soulitems/-blöcke hinzu ( siehe http://lycanitesmobs.com/item ) womit sich bspw. seltene Monster beschwören und Mounts/Pets zum beschwören an einen Soulstone binden lassen. IHMO unproblematisch. 
- [x] OpenBlocks + Lib updaten? **ja +1** / ~~nein~~
- Building Guide wurde verändert und in 2 varianten verpackt.
- Rotating Elevator, ändert die Sichtrichtung beim Etagenwechsel, finde ich ganz nett.
- Item Epic Eraser, ist mir noch nicht klar was der macht... 
- [x] Blood Magic updaten? **ja +1** / ~~nein~~
- Soweit es von den Changelogs zu beurteilen ist nur fixes und es wird in der 1.7.10 wohl auch keine Feature updates geben. 
- [x] BuildCraft + Compat updaten? **ja +1** / ~~nein~~
- Clay Transport Pipe + Fluid Variante, versucht etwas in ein Inventar einzufügen, wenn nicht möglich weil voll wird es das Netz weiter entlang gereicht, sprich verhindert das rausrutschen aus den Pipes.
- Power Adapter, Strom Anschluss für Pipes anstatt eine Redstone Engine zum rausziehen aus einem Inventar lässt sich die bspw. Wooden Pipe via Adapter mit Strom betreiben, sofern der Stromanschluss sich nicht eh schon mit der Wooden Pipe verbinden bspw. Thermal Dynamics. 
- [x] BuildCraft Additions updaten? **ja +1** / ~~nein~~
- Soweit ich das sehen kann gibt es da als neues Item nur die Hover Boots, die soweit ich das sehen kann Fallschaden absorbieren. Das Item wirkt aber noch unfertig (Texturenfehler) 
- [x] Botania updaten? **ja** / ~~nein~~ ( siehe https://github.com/combak/ShatteredWorld/issues/180 )
- Von unseren Build 192 bis zum aktuellen Build 249 gab es extrem viele Änderungen ( siehe http://botaniamod.net/changelog.php ) IMHO brauch es dafür ein eigenes Update. 
- [x] Thermal Expansion updaten? **ja** / ~~nein~~
- Neu Machinist's Workbenches, Crafting Table mit Chest und der Möglichkeit Rezepte mit Schematics zu speichern. Nur fürs Manuelle Crafting.
- Mehr sehe ich auf den ersten Blick nicht an neuem aber alles geänderten Rezepte, Scripts etc. wird man nach dem Update noch prüfen müssen.
- Release Notes sagen noch folgende neuen Items an: Item Allocator (quasi ein besserer Hopper), Charge Plate ( imho das selbe wie das Charge Pad bloß flach), Excursion Plate (schiebt Entites bis zu 26 Blöcke von sich weg) und Teleporter Plate (Teleport über Raum und Dimensionen). 
- [x] Tinkers Construct updaten? **ja** / ~~nein~~
- Sind nur Bugfixes und ein paar Deko Blöcke hinzugekommen
- Wie bei allen anderen auch unsere Scripts müssen nach einem Update gecheckt werden, was bei Tinkers nicht wenig ist. 
- [x] Thaumcraft - Automagy updaten? **ja** / ~~nein~~ ( siehe https://github.com/combak/ShatteredWorld/issues/179 )
- Alle neueren Updates sind beta aber der ganze Mod scheint noch beta zu sein
- Es gibt viele Änderungen zwischen unserer Version 0.22.2 und der aktuellen 0.28.2 ( siehe Changelog http://minecraft.curseforge.com/projects/automagy/files/2285272 ) und ich hab zu wenig Ahnung von Thaumcraft um das neue Zeugs beurteilen zu könne. 
- [x] Thaumcraft - Forbidden Magic updaten? **ja** / ~~nein~~ ( siehe https://github.com/combak/ShatteredWorld/issues/179 )
- Aktuellste Version ist ein stable Release
- Neue Dragon Slayer Sword, durch Iquana crafting only
- Neu Terrasteel Caps
- Neu Crystal Scribing Tools, kA für was das gut ist.
- Neu Heretic Villagers, kA wann wie oder warum die auftauchen.
- Neu  Profane Wand, noch ein Stab mehr
- Auch hier gilt, ich hab wenig Ahnung von der Mod um fachkundige Meinung wird gebeten 
- [x] Draconic Evolution updaten? **ja** / ~~nein~~
- BandonsCore als neue Abhängigkeit, zur Erinnerung, um es in die Licences zu übernehmen. ^^
- Schön ausführliches Changelog und es gab einige Änderungen: https://github.com/brandon3055/Draconic-Evolution/blob/master/Change%20Log.txt
- Draconium Blöcke stehen jetzt im OreDict, müssen aus unserem Script entfernt werden.
- Neu Draconium Infused Obisidian, ein wither proof block, sollte deaktiviert werde.
- Draconic Portal, wird aus Draconium Infused Obisidian und dem Dislocator gebaut und ist ein Teleport zu einem ausgewählten Punkt.
- Neu Draconic Reactor, kann richtig übel explodieren(!) ^^, Fuel awakened draconium, sieht alles im allen komplex und interessant aus siehe https://www.youtube.com/watch?v=jBgXRTL9EkE
- Neu Flow Gates (RF&Fluid) kontrolliert wie der Name schon sagt den Fluss wie viel RF oder Fluid durch das Gate laufen. Wird bspw für den Reaktor benötigt.
- Neu Draconium und Awakended Nuggets. Scripts für die Tinkers schmelze anpassen.
- Neu Chaos Crystal, Shard und Fragment, wird zum bauen des Reaktors benötigt.
- Neu Chaos Island, ein neuer Bereich im End, Boss Chaos Dragon, prüfen ob sich das mit Hardcore Ender Expansion verträgt. 
- Neu Item Dislocator, Magnet der Items ins Inventar zieht, in normal 8 Blöcke und Awakened 32 Blöcke Entfernung. Letzteres finde ich zuviel auch wenn das Ding scheiße teuer ist.

Fortsetzung folgt.

**Comment by DerOliDE** [comment]
**Mod Updates:**

Bereits geupdatet:
- Ars Magica2 ( überwiegend fixes, ein neues Item "Sealed Door" checken )
- Forestry sprung auf Version 4 ( Änderungen müssen geprüft werden )
- Binnie Mods + Binnie Patcher für Forestry 4 ( Änderungen müssen geprüft werden )
- Custom NPCs Version d Feb.2016 ( zu prüfen ob gefixt bzw noch vorhanden https://github.com/combak/ShatteredWorld/issues/172 )
- ModTweaker2 ( Warning prüfen )
- NEI Addons
- NEI Integration
- AppleCore ( für Spice of Life )
- The Spice of Life
- Auto Packager
- BiblioCraft ( ein neuer Block Framed Chest und ein neues Item Stockroom Catalog )
- Carpenters Block ( Keine neuen Blöcke überwiegend fixes )
- CookieCore ( für Tinkers Steelworks )
- Custom Main Menu
- Hardcore Darkness
- Hardcore Questing Mode ( Questbook checken )
- Mantle ( für Tinkers Stuff )
- TiC Tooltips
- Waila Harvestability
- Backpacks ( Nur Bugfixes )
- CoFHCore ( für Team CoFH Geraffel )
- Redstone Arsenal ( Bugfixes + Harvestlevel für Wrench(?) lässt sich ja zur Not via Iquana deaktivieren )
- Nether Ores ( Nur Bugfixes )
- Thermal Foundation ( Nur Bugfixes )
- Hardcore Ender Expansion ( Bugfix + Musik in Resource Pack ausgelagert )
- Simply Jetpacks ( Nur Bugfixes )
- Extra Cells2 ( Bugfixes + Gas und OpenComputers Anbindungen, die uns z.Z nicht betreffen )
- EnderTech ( Nur Bugfixes )
- Tinker Mechworks ( Nur Bugfixes )
- Tinker Steelworks  ( Nur Bugfixes )
- Thaumcraft - Travellers Gear ( Nur Bugfixes )
- Adv. Generators
- AE2 Stuff
- Blood Magic
- BuildCraft + Compat
- BuildCraft Additions 
- Extra Utilities
- Lycanite Mobs
- Open Blocks + Lib
- Thermal Expansion ( wirkt auf den ersten Blick unproblematisch )
- Draconic Evolution
- Tinker Construct
- BdLib ( für AE2 Stuff + Adv. Generator. Fehler ohne Adv. Generators update )
- Botania ( ggf. als eigenes Update, da dort extrem viel geändert wurde. )
- Not Enough Keys ( 3.0.0b45 Tinkers Armor GUI öffnet sich und lässt sich nicht mehr schließen siehe https://www.reddit.com/r/feedthebeast/comments/3k9wc4/i_either_found_a_bug_or_screwed_something_up/ in TConstruct 1.8.8 gefixt )
- Pams Harvestcraft
- Thaumcraft - Automagy ( viele Änderungen )

Vermutlich problemlos: 
- ~~Animation API~~ ( Keine neuere Version vorhanden )
- ~~Baubles~~ ( Keine neuere Version vorhanden )
- ~~Chicken Bones Mods ( NEI + Core )~~ ( Keine neuere Version vorhanden )
- ~~Enchiridion~~ ( Keine neuere Version vorhanden )
- ~~Eureka ( für BuildCraft Additions )~~ ( Keine neuere Version vorhanden )
- ~~FastCraft~~ ( Kein neuerer stable build )
- ~~Fun World Gen~~ ( Wird ja offensichtlich nicht weiterentwickelt )
- ~~Guide API~~ ( Kein neuerer stable build )
- ~~Iguanas Tinkers Tweaks~~ ( Keine neuere Version vorhanden )
- ~~INpureCore~~ ( Wird nicht mehr gepflegt siehe https://github.com/combak/ShatteredWorld/issues/181 )
- ~~Inventory Tweaks~~ ( Keine neuere Version vorhanden )
- ~~MineTweaker3~~ ( Keine neuere Version vorhanden bzw. noch ohne sorting )
- ~~MobiusCore ( für Opis )~~ ( Keine neuere Version vorhanden )
- ~~NEI - Not Enough Resources~~ ( Kein neuerer stable build )
- ~~Opis~~ ( Keine neuere Version vorhanden )
- ~~Resource Loader~~ ( Keine neuere Version vorhanden )
- ~~ttCore ( für Waila )~~ ( Kein neuerer stable build )
- ~~Waila~~ ( Keine neuere Version vorhanden )
- ~~Waila Plugins~~ ( Kein neuerer stable build )
- Forge Essentials ( Zuletzt, sobald die Server-Version gebastelt wird )

Eventuell mit Problemen durch bspw. neue Blöcke:
- ~~AE2~~ ( Kein neuerer stable build )
- ~~Chisel2~~ ( Keine neuere Version vorhanden )
- ~~EnderIO~~ ( Kein neuerer stable build )
- ~~Ex Astris + Nihilo~~ ( Keine neuere Version vorhanden )
- ~~iBench~~ ( Keine neuere Version vorhanden )
- ~~Iron Chests~~ ( Keine neuere Version vorhanden )
- ~~Natura~~ ( Kein stable update verfügbar )
- ~~Project Red~~ ( Nur neuere pre builds verfügbar )
- ~~Thermal Dynamics~~ ( Keine neuere Version vorhanden )
- ~~Thaumcraft~~ ( Keine neuere Version vorhanden )
- ~~Thaumcraft - Magistics~~ ( Keine neuere Version vorhanden )
- ~~Thaumcraft - MobAspects~~ ( Keine neuere Version vorhanden )
- ~~Thaumcraft - Witching Gadgets~~ ( Keine neuere Version vorhanden )
- ~~Thaumcraft - Thaumic Energistics~~ ( Keine neuere Version vorhanden )

Mit Problemen verbunden:
- AgriCraft ( Version 1.5.0 crash beim start )
- Storage Drawers + Addon Packs ( Version 1.9.4 crash beim start )
- Garden Stuff ( Version 1.7.0 crash beim start )

**Comment by Nedelosk** [comment]
Aha es geht weiter, dann kann ich mich mal wieder ans Werk machen.

**Comment by DerOliDE** [comment]
Ja, ich will diesen Monat mal wieder alles auf einen aktualisierten Stand bringen was möglich ist und eine neue Version raus bringen, ob mit oder ohne Multiworld (alternative). Es sammelt sich sonst nur immer mehr an.

**Comment by DerOliDE** [comment]
**Push** Bei Gelegenheit mal im ersten Post den "Mods update?" Abschnitt durch den Kopf gehen lassen, um Meinungen wird gebeten.

**Comment by krakel** [comment]
Lycanite Mobs updaten? ja
aktuell ist: 1.13.0.5
wir haben: 1.11.0.1
- da sind viele Bugfixes drin, auch einige neue config-Möglichkeiten
- das binden und benutzen von Pets/Mounts ist nicht so einfach, wie es sich anhört

**Comment by krakel** [comment]
AE2 Stuff updaten? ja
diese Wireless Connection ist wohl recht teuer und geht auch nur in der gleichen Dimension

**Comment by krakel** [comment]
Blood Magic updaten? ja
- scheint unbedenklich zu sein
- Bitte die Guide-API nicht vergessen (falls neue Version in 1.7.10, aktuell nur Beta)

**Comment by DerOliDE** [comment]
Ich möchte wenn möglich nur auf Release Versionen updaten und da gibt es für die Guide API keine neuere. Wenn ich zwingend eine neuere brauche werde ich auch eine alpha oder beta nehmen.

**Comment by DerOliDE** [comment]
**Noch ein Push** Alle Mods durchleuchtet und das letzte mal nerven: "Bei Gelegenheit mal im ersten Post den "Mods update?" Abschnitt durch den Kopf gehen lassen, um Meinungen wird gebeten." ;-)

**Comment by BakermanLP** [comment]
BdLib ( für AE2 Stuff + Adv. Generator. Fehler ohne Adv. Generators update )

Kannst du problemlos machen, es sind nur Fehlerbereinigungen und ein paar Items aus anderen Mods sind Kompatibel gemacht worden.

Open Blocks + Lib sind so weit ich das gesehen habe auch nur Fehlerbereinigungen.

Warum bei dir Agricraft und Storage Drawers crashen verstehe ich nicht, bei RETv8 in der DEV Version gehen die.

**Comment by DerOliDE** [comment]
Bei OpenBlocks ist es nicht nur Fehlerbereinigung, die geänderten und neuen Blöcke habe ich oben angesprochen, sollten keine Probleme machen aber ich hab kein Plan was der Epic Eraser macht.

Ich habe mich nicht lange mit den Fehlern beim Crash befasst, ich will erst einmal das reinstopfen was vermeintlich problemlos verläuft. ^^

**Comment by DerOliDE** [comment]
Eine Woche lasse ich das hier noch laufen, zu Mods zu denen keine Meinung abgegeben wird, nehme ich mir das Recht raus selbst zu entscheiden, wenn ich zu wenig Knowhow zum abschätzen des Updates habe, wie bei Thaumcraft, oder mir der Aufwand zu groß erscheint, wird es kein Update der entsprechenden Mods geben.  

Bei +4 auf einem ja oder nein ist es für mich sofort beschlossen, da es die Hälfte der ComBak beteiligten ist.

P.S.: Notiz an mich selbst, dass nächste mal jede Entscheidung in einem separaten Comment packen, dann kann man das mit dem neuen Smilie System (Thumps up/down) leichter auswerten. ^^

**Comment by DerOliDE** [comment]
Wenn ich heute Abend nicht zu spät nachhause komme packe ich noch die Version 0.7.2 zusammen.

**Comment by DerOliDE** [comment]
Soweit alles fertig, morgen muss ich noch die Server Version testen und dann packe ich alles zusammen.

**Comment by DerOliDE** [comment]
@Nedelosk Gibt es heute oder morgen noch eine neue Version für Forest Day?

**Comment by Nedelosk** [comment]
Nein

**Comment by DerOliDE** [comment]
Damit wären dann alle Punkte abgeschlossen.

**Comment by Nedelosk** [comment]
@DerOli82 Wann bringst du die neue Version raus ?

**Comment by DerOliDE** [comment]
Morgen muss die Server Version noch testen.

Am 31.03.2016 um 15:45 schrieb Nedelosk:
