### ISSUE TITLE
Checklist 0.7.3

### ISSUE THREAD

**Issue by DerOliDE** [combak/ShatteredWorld#182]
- [x] Versuche Mods zu updaten bei denen es in 0.7.2 Probleme gab.
-  ~~AgriCraft ( Version 1.5.0 crash beim start )~~ läuft
- ~~Storage Drawers + Addon Packs ( Version 1.9.4 crash beim start )~~ läuft
- ~~Garden Stuff ( Version 1.7.0 crash beim start )~~ läuft
- [x] ~~Ore Processing checken. ( https://github.com/combak/ShatteredWorld/issues/61 )~~ Auf 0.7.4 verschoben
- [x] Botania checken. ( https://github.com/combak/ShatteredWorld/issues/180 )
- [x] Thaumcraft Addons checken. ( https://github.com/combak/ShatteredWorld/issues/179 )
- ~~Automagy~~ erledigt
- ~~Forbidden Magic~~ erledigt
- ~~Travellers Gear~~ erledigt
- [x] HarvestCraft + Spice of Life checken. ( https://github.com/combak/ShatteredWorld/issues/178 )
- [x] CustomNPC Teleporter checken. ( https://github.com/combak/ShatteredWorld/issues/172 )
- [x] Custom Rezepte checken.
- [x] Auf dem Server checken wie viel "schaden" das entfernen von Natura angerichtet hat.

Fortsetzung folgt.

**Comment by Grambosch** [comment]
HarvestCraft Spice of Life : Die ganzen sachen die in den Foodgroups fehlen sind in der Json aber hinterlegt komme grade nicht drauf woran es liegt

**Comment by DerOliDE** [comment]
Ein Beispiel zur Orientierung?

**Comment by Grambosch** [comment]
Die Kuchen die ich gestern nannte die nicht drin sind stehen in der SoL Config  unter Oredict wohl schon alle drin zB

**Comment by DerOliDE** [comment]
Etwas heimtückisch das teilt sich in Cake und Pie auf nur das in Cake alle drin stehen und Pie die überschreibt.

**Comment by Grambosch** [comment]
Natura wäre mir übbrigens nix aufgefallen

**Comment by DerOliDE** [comment]
TODO
Arcane Bore (Thaumcraft) deaktivieren, kann als Block Breaker genutzt werden.

**Comment by krakel** [comment]
Die Avariata Waffen und Werkzeuge sind alle standardmäßig deaktiviert.

**Comment by DerOliDE** [comment]
Schau mal in die Commits rein ;-)

**Comment by Grambosch** [comment]
Nur falls ichs vergessen haben sollte: Sollen die BC Additions Dust nicht in der TC Schmelze wiederverwertbar sein?

**Comment by DerOliDE** [comment]
Dust schaue ich mir die Tage mal an, würde Sinn machen diese wieder einschmelzen zu können, ich muss ja sowieso noch meine Ore Processing Liste abarbeiten.

**Comment by Grambosch** [comment]
Heat Conducting Plates (BCA) sollten evtl im Ofen schmelzbar sein da sie im ersten Questkapitel im Autopackager gebraucht werden

**Comment by DerOliDE** [comment]
Mäh Apple Milk and Tea fügt Erze und Verarbeitung hinzu, die ich nicht tweaken kann :-S

**Comment by BakermanLP** [comment]
Geht doch ... https://minecraft.curseforge.com/projects/amtweaker

**Comment by DerOliDE** [comment]
Dann halt mäh noch mehr kram zum tweaken ^^

**Comment by DerOliDE** [comment]
Wird zeit das ich mein auto tweaker fertig programmiere ...

**Comment by Grambosch** [comment]
Ich ha da so ein Problem mit Limited Ressources... Hab nen Igneous Extruder aufgebaut , wollte ihn umsetzen das wurde nicht erkannt und nu darf ich keinen mehr setzen. Ich versuch noch was rum aber das sollte ja nicht so sein

**Comment by Grambosch** [comment]
Hab den Extruder nochmal an den "originalplatz" gesetzt und dann konnte ich ihn korrekt abbauen und neusetzen

**Comment by DerOliDE** [comment]
Wie hast Du ihn abgebaut? Wrench Pickaxe?

**Comment by Grambosch** [comment]
Pickaxe
